version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keep
    ports:
      - "5432:5432"
    volumes:
    - dbdata:/var/lib/postgresql/data
  api:
    build: .
    depends_on:
      - db
    environment:
      PORT: 4000
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/keep?schema=public
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "4000:4000"
    command: sh -c "npx prisma generate && npx prisma db push && node src/server.js"
volumes:
  dbdata: